image: node:10.15.3

cache:
  untracked: true
  paths:
    - node_modules/

stages:
  - test
  - staging
  - deploy

# lint and test are two different jobs in the same stage.
# This allows us to run these two in parallel and making build faster

lint:
  stage: test
  script:
    - yarn install
    # - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - yarn run lint

test:
  stage: test
  script:
    - yarn install
    # - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - yarn run test:unit

# staging:
#     type: deploy
#     stage: staging
#     image: ruby:latest
#     script:
#       - apt-get update -qy
#       - apt-get install -y ruby-dev
#       - gem install dpl
#       - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
#     only:
#         - develop

# deploy:dev:
#   stage: deploy
#   script:
#     - bash deploy/deploy.sh
#   only:
#     - master
deploy:
  stage: deploy
  script:
    - yarn i -g netlify-cli
    - yarn run build
    - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  dependencies:
    - test
  only:
    - develop
